title: Dr. Jonathan Barichivich # your name (or website title) here
logo: "/images/picture_small.jpg?raw=true" # your photo (or logo) here /images/picture_small.jpg?raw=true or /images/PHOTO-2021-08-05-17-19-10.jpg?raw=true
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br> Global climate and ecosystem science <br>
  <a href="https://scholar.google.cl/citations?hl=en&user=134gvMcAAAAJ/">See me in GoogleScholar</a> 
  
theme: jekyll-theme-minimal
google_analytics: G-JCQS0WN55M
