title: Dr. Jonathan Barichivich # your name (or website title) here
logo: "/images/picture_small.jpg?raw=true" # your photo (or logo) here /images/picture_small.jpg?raw=true or /images/PHOTO-2021-08-05-17-19-10.jpg?raw=true
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br> Global climate and ecosystem science <br>
  <a href="https://scholar.google.cl/citations?hl=en&user=134gvMcAAAAJ/">See me in GoogleScholar</a> 
  
theme: jekyll-theme-minimal
google_analytics: G-DSYGM3527C # UA-206768013-1 #UA-000000-0 # your Google Analytics tracking ID here, To set up correctly see: https://www.youtube.com/watch?v=9yc0T4tR4gg and https://www.youtube.com/watch?v=QfUSKYJz5QE
# https://support.google.com/analytics/answer/10269537?hl=en 
# github-pages-GA4 asociated tag inside streams: UA-206781572-1 
